using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Godot;
using Structures.Resources;

namespace UtilityLibrary.DataLoading;

/// <summary>
/// Writes <see cref="SubtypeDefinition"/> records to Configuration/Subtypes/&lt;family&gt;_subtypes.yaml.
/// Single code path shared by the BiomeEditor and the Planet Generator subtype editor so emission
/// is byte-identical regardless of the source UI.
/// </summary>
public static class SubtypeYamlIO
{
    public const string SubtypesDir = "res://Configuration/Subtypes";

    public static string FilePath(BodyFamily family) => family switch
    {
        BodyFamily.RockyPlanet => $"{SubtypesDir}/rocky_subtypes.yaml",
        BodyFamily.GasGiant => $"{SubtypesDir}/gas_giant_subtypes.yaml",
        BodyFamily.IceGiant => $"{SubtypesDir}/ice_giant_subtypes.yaml",
        BodyFamily.DwarfPlanet => $"{SubtypesDir}/dwarf_planet_subtypes.yaml",
        BodyFamily.Star => $"{SubtypesDir}/star_subtypes.yaml",
        BodyFamily.NeutronStar => $"{SubtypesDir}/neutron_star_subtypes.yaml",
        BodyFamily.BlackHole => $"{SubtypesDir}/black_hole_subtypes.yaml",
        BodyFamily.Satellite => $"{SubtypesDir}/satellite_subtypes.yaml",
        BodyFamily.Belt => $"{SubtypesDir}/belt_subtypes.yaml",
        _ => $"{SubtypesDir}/rocky_subtypes.yaml",
    };

    /// <summary>
    /// Writes every <see cref="BodyFamily"/> file. Empty families are written as a stub
    /// (header comment + <c>subtypes: []</c>) so callers can never end up with a missing file.
    /// </summary>
    public static void WriteAll(IEnumerable<SubtypeDefinition> definitions)
    {
        ArgumentNullException.ThrowIfNull(definitions);
        var byFamily = definitions
            .Where(d => !string.IsNullOrEmpty(d.Id))
            .GroupBy(d => d.Family)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (BodyFamily family in Enum.GetValues<BodyFamily>())
        {
            byFamily.TryGetValue(family, out var list);
            WriteFamily(family, list ?? new List<SubtypeDefinition>());
        }
    }

    public static void WriteFamily(BodyFamily family, IReadOnlyList<SubtypeDefinition> definitions)
    {
        ArgumentNullException.ThrowIfNull(definitions);

        var sorted = definitions
            .Where(d => !string.IsNullOrEmpty(d.Id))
            .OrderBy(d => d.Id, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine($"# {family} subtypes. Auto-generated by SubtypeYamlIO.");
        sb.AppendLine();
        sb.AppendLine("subtypes:");

        if (sorted.Count == 0)
        {
            WriteText(FilePath(family), sb.ToString().TrimEnd('\r', '\n') + " []\n");
            return;
        }

        bool first = true;
        foreach (var s in sorted)
        {
            if (!first) sb.AppendLine();
            first = false;
            Indent(sb, 1, $"- id: {s.Id}");
            Indent(sb, 2, $"display_name: {YamlScalar(s.DisplayName)}");
            Indent(sb, 2, $"atmosphere_min: {FormatFloat(s.AtmosphereMin)}");
            Indent(sb, 2, $"atmosphere_max: {FormatFloat(s.AtmosphereMax)}");
            Indent(sb, 2, $"base_hazard: {FormatFloat(s.BaseHazard)}");
            Indent(sb, 2, $"base_resource_weight: {FormatFloat(s.BaseResourceWeight)}");
            Indent(sb, 2, $"moisture_mode: {s.MoistureMode}");
            if (s.MoistureParams.Count > 0)
            {
                Indent(sb, 2, "moisture_params:");
                foreach (var mp in s.MoistureParams.OrderBy(k => k.Key, StringComparer.Ordinal))
                    Indent(sb, 3, $"{mp.Key}: {FormatFloat(mp.Value)}");
            }
            if (s.AssignerRules.Count > 0)
            {
                Indent(sb, 2, "assigner_rules:");
                foreach (var rule in s.AssignerRules)
                {
                    Indent(sb, 3, $"- biome_id: {rule.BiomeId}");
                    var conds = new List<string>();
                    if (rule.HeightAbove.HasValue) conds.Add($"height_above: {FormatFloat(rule.HeightAbove.Value)}");
                    if (rule.HeightBelow.HasValue) conds.Add($"height_below: {FormatFloat(rule.HeightBelow.Value)}");
                    if (rule.MoistureAbove.HasValue) conds.Add($"moisture_above: {FormatFloat(rule.MoistureAbove.Value)}");
                    if (rule.MoistureBelow.HasValue) conds.Add($"moisture_below: {FormatFloat(rule.MoistureBelow.Value)}");
                    if (rule.AbsLatitudeAbove.HasValue) conds.Add($"abs_latitude_above: {FormatFloat(rule.AbsLatitudeAbove.Value)}");
                    if (rule.AbsLatitudeBelow.HasValue) conds.Add($"abs_latitude_below: {FormatFloat(rule.AbsLatitudeBelow.Value)}");
                    string when = conds.Count == 0 ? "{}" : "{ " + string.Join(", ", conds) + " }";
                    Indent(sb, 4, $"when: {when}");
                }
            }
            WriteStringList(sb, "resource_groups", s.ResourceGroups);
            WriteStringList(sb, "add_resources", s.AddResources);
            WriteStringList(sb, "remove_resources", s.RemoveResources);
            WriteMeshBlock(sb, s.MeshRanges, s.VerticesPerEdgeRanges);
            WriteTectonicsBlock(sb, s.TectonicRanges, s.SampleVelocityAtEdgeMidpoint);
            WriteRangeBlock(sb, "spherical_harmonics", s.SphericalHarmonicsRanges);
        }

        WriteText(FilePath(family), sb.ToString());
    }

    // ── Formatting helpers ──────────────────────────────────────────────

    private static void WriteRangeBlock(StringBuilder sb, string blockKey, Dictionary<string, FloatRange> ranges)
    {
        if (ranges.Count == 0) return;
        Indent(sb, 2, $"{blockKey}:");
        foreach (var kvp in ranges.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            var r = kvp.Value;
            Indent(sb, 3, $"{kvp.Key}: [{FormatFloat(r.Min)}, {FormatFloat(r.Max)}]");
        }
    }

    /// <summary>
    /// Tectonics block emits the scalar ranges (as <see cref="WriteRangeBlock"/>) plus the
    /// <c>sample_velocity_at_edge_midpoint</c> bool flag, emitted last. Skipped entirely when
    /// there are no tectonic ranges (non-tectonic families).
    /// </summary>
    private static void WriteTectonicsBlock(StringBuilder sb, Dictionary<string, FloatRange> ranges, bool sampleVelocityAtEdgeMidpoint)
    {
        if (ranges.Count == 0) return;
        Indent(sb, 2, "tectonics:");
        foreach (var kvp in ranges.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            var r = kvp.Value;
            Indent(sb, 3, $"{kvp.Key}: [{FormatFloat(r.Min)}, {FormatFloat(r.Max)}]");
        }
        Indent(sb, 3, $"sample_velocity_at_edge_midpoint: {(sampleVelocityAtEdgeMidpoint ? "true" : "false")}");
    }

    /// <summary>
    /// Mesh block emits scalar ranges (subdivisions, num_abberations, num_deformation_cycles)
    /// plus the per-subdivision-level <c>vertices_per_edge</c> list. Both are optional.
    /// </summary>
    private static void WriteMeshBlock(
        StringBuilder sb,
        Dictionary<string, FloatRange> ranges,
        List<FloatRange> verticesPerEdge)
    {
        if (ranges.Count == 0 && verticesPerEdge.Count == 0) return;
        Indent(sb, 2, "mesh:");
        foreach (var kvp in ranges.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            var r = kvp.Value;
            Indent(sb, 3, $"{kvp.Key}: [{FormatFloat(r.Min)}, {FormatFloat(r.Max)}]");
        }
        if (verticesPerEdge.Count > 0)
        {
            Indent(sb, 3, "vertices_per_edge:");
            foreach (var r in verticesPerEdge)
                Indent(sb, 4, $"- [{FormatFloat(r.Min)}, {FormatFloat(r.Max)}]");
        }
    }

    private static void WriteStringList(StringBuilder sb, string key, List<string> items)
    {
        if (items.Count == 0)
        {
            Indent(sb, 2, $"{key}: []");
            return;
        }
        Indent(sb, 2, $"{key}: [{string.Join(", ", items)}]");
    }

    private static void Indent(StringBuilder sb, int level, string content)
    {
        sb.Append(' ', level * 2).AppendLine(content);
    }

    private static string YamlScalar(string s)
    {
        if (string.IsNullOrEmpty(s)) return "\"\"";
        if (s.IndexOfAny(new[] { ':', '#', '\'', '"', '[', ']', '{', '}', '\n', ',' }) >= 0)
            return "\"" + s.Replace("\"", "\\\"") + "\"";
        return s;
    }

    private static string FormatFloat(float value)
    {
        if (Mathf.IsEqualApprox(value, Mathf.Round(value)))
            return ((int)value).ToString(CultureInfo.InvariantCulture);
        return value.ToString("0.######", CultureInfo.InvariantCulture);
    }

    private static void WriteText(string filePath, string content)
    {
        var file = Godot.FileAccess.Open(filePath, Godot.FileAccess.ModeFlags.Write);
        if (file == null)
        {
            var err = Godot.FileAccess.GetOpenError();
            throw new InvalidOperationException($"SubtypeYamlIO: cannot write {filePath} ({err})");
        }
        try { file.StoreString(content); }
        finally { file.Close(); }
    }
}
