#if DEBUG
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Godot;
using ProceduralGeneration.BiomeSystem;
using Structures.Enums;
using Structures.Resources;
using UtilityLibrary;
using YamlDotNet.Serialization;

namespace DeveloperTools.BiomeEditor;

/// <summary>
/// Writes BiomeEditorModel contents back to disk across the five source YAML files.
/// Files fully owned by the editor (assigner config, biome resource config, resource groups)
/// are emitted from scratch; multi-section files (planetary_resource_config, SystemGen)
/// are loaded into a dictionary, mutated in place, and re-serialized to preserve unrelated keys.
/// </summary>
public static class BiomeEditorYamlIO
{
    public static void WriteAll(BiomeEditorModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        WriteAssignerConfig(model);
        WriteBiomeResourceConfig(model);
        WritePlanetaryResourceConfig(model);
        WriteResourceGroups(model);
        WriteAtmosphereTemplates(model);
        WriteBiomes(model);
        WriteSubtypes(model);

        // Reset dirty flags.
        foreach (var a in model.Assigners.Values) a.IsDirty = false;
        foreach (var b in model.BiomeResources.Values) b.IsDirty = false;
        foreach (var s in model.SubtypeResources.Values) s.IsDirty = false;
        foreach (var g in model.ResourceGroups) { g.IsDirty = false; g.IsNew = false; }
        foreach (var t in model.AtmosphereTemplates.Values) t.IsDirty = false;
        foreach (var bd in model.Biomes.Values) { bd.IsDirty = false; bd.IsNew = false; }
        foreach (var sd in model.Subtypes.Values) { sd.IsDirty = false; sd.IsNew = false; }
    }

    // ── Biome definitions (biomes.yaml) ─────────────────────────────────

    private static void WriteBiomes(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Biome registry. Auto-generated by BiomeEditor.");
        sb.AppendLine("# Single source of truth for biome IDs, display names, colors per subtype,");
        sb.AppendLine("# hazard, geothermal vent probability, resource weight modifiers, and tags.");
        sb.AppendLine();
        sb.AppendLine("biomes:");

        bool first = true;
        foreach (var kvp in model.Biomes.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            var b = kvp.Value;
            if (string.IsNullOrEmpty(b.Id)) continue;
            if (!first) sb.AppendLine();
            first = false;
            YamlIndent.AppendLine(sb, 1, $"- id: {b.Id}");
            YamlIndent.AppendLine(sb, 2, $"display_name: {YamlScalar(b.DisplayName)}");
            YamlIndent.AppendLine(sb, 2, $"default_color: \"{FormatHex(b.DefaultColor)}\"");
            if (b.ColorOverrides.Count > 0)
            {
                YamlIndent.AppendLine(sb, 2, "color_overrides:");
                foreach (var ov in b.ColorOverrides.OrderBy(k => k.Key, StringComparer.Ordinal))
                    YamlIndent.AppendLine(sb, 3, $"{ov.Key}: \"{FormatHex(ov.Value)}\"");
            }
            YamlIndent.AppendLine(sb, 2, $"hazard_weight: {FormatFloat(b.HazardWeight)}");
            YamlIndent.AppendLine(sb, 2, $"geothermal_vent_probability: {FormatFloat(b.GeothermalVentProbability)}");
            if (b.ResourceWeightModifiers.Count > 0)
            {
                YamlIndent.AppendLine(sb, 2, "resource_weight_modifiers:");
                foreach (var rw in b.ResourceWeightModifiers.OrderBy(k => k.Key, StringComparer.Ordinal))
                    YamlIndent.AppendLine(sb, 3, $"{rw.Key}: {FormatFloat(rw.Value)}");
            }
            if (b.Tags.Count > 0)
            {
                YamlIndent.AppendLine(sb, 2, $"tags: [{string.Join(", ", b.Tags)}]");
            }
        }

        WriteText(BiomeEditorModel.BiomesDefinitionPath, sb.ToString());
    }

    // ── Subtype definitions (Configuration/Subtypes/<family>_subtypes.yaml) ─

    private static void WriteSubtypes(BiomeEditorModel model)
    {
        foreach (BodyFamily family in Enum.GetValues<BodyFamily>())
            WriteSubtypeFamily(model, family);
    }

    private static void WriteSubtypeFamily(BiomeEditorModel model, BodyFamily family)
    {
        var familySubs = model.Subtypes.Values
            .Where(s => s.Family == family && !string.IsNullOrEmpty(s.Id))
            .OrderBy(s => s.Id, StringComparer.Ordinal)
            .ToList();
        if (familySubs.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine($"# {family} subtypes. Auto-generated by BiomeEditor.");
        sb.AppendLine();
        sb.AppendLine("subtypes:");

        bool first = true;
        foreach (var s in familySubs)
        {
            if (!first) sb.AppendLine();
            first = false;
            YamlIndent.AppendLine(sb, 1, $"- id: {s.Id}");
            YamlIndent.AppendLine(sb, 2, $"display_name: {YamlScalar(s.DisplayName)}");
            YamlIndent.AppendLine(sb, 2, $"atmosphere_min: {FormatFloat(s.AtmosphereMin)}");
            YamlIndent.AppendLine(sb, 2, $"atmosphere_max: {FormatFloat(s.AtmosphereMax)}");
            YamlIndent.AppendLine(sb, 2, $"base_hazard: {FormatFloat(s.BaseHazard)}");
            YamlIndent.AppendLine(sb, 2, $"base_resource_weight: {FormatFloat(s.BaseResourceWeight)}");
            YamlIndent.AppendLine(sb, 2, $"moisture_mode: {s.MoistureMode}");
            if (s.MoistureParams.Count > 0)
            {
                YamlIndent.AppendLine(sb, 2, "moisture_params:");
                foreach (var mp in s.MoistureParams.OrderBy(k => k.Key, StringComparer.Ordinal))
                    YamlIndent.AppendLine(sb, 3, $"{mp.Key}: {FormatFloat(mp.Value)}");
            }
            if (s.AssignerRules.Count > 0)
            {
                YamlIndent.AppendLine(sb, 2, "assigner_rules:");
                foreach (var rule in s.AssignerRules)
                {
                    YamlIndent.AppendLine(sb, 3, $"- biome_id: {rule.BiomeId}");
                    var conds = new List<string>();
                    if (rule.HeightAbove.HasValue) conds.Add($"height_above: {FormatFloat(rule.HeightAbove.Value)}");
                    if (rule.HeightBelow.HasValue) conds.Add($"height_below: {FormatFloat(rule.HeightBelow.Value)}");
                    if (rule.MoistureAbove.HasValue) conds.Add($"moisture_above: {FormatFloat(rule.MoistureAbove.Value)}");
                    if (rule.MoistureBelow.HasValue) conds.Add($"moisture_below: {FormatFloat(rule.MoistureBelow.Value)}");
                    if (rule.AbsLatitudeAbove.HasValue) conds.Add($"abs_latitude_above: {FormatFloat(rule.AbsLatitudeAbove.Value)}");
                    if (rule.AbsLatitudeBelow.HasValue) conds.Add($"abs_latitude_below: {FormatFloat(rule.AbsLatitudeBelow.Value)}");
                    string when = conds.Count == 0 ? "{}" : "{ " + string.Join(", ", conds) + " }";
                    YamlIndent.AppendLine(sb, 4, $"when: {when}");
                }
            }
            WriteStringList(sb, "resource_groups", s.ResourceGroups);
            WriteStringList(sb, "add_resources", s.AddResources);
            WriteStringList(sb, "remove_resources", s.RemoveResources);
            WriteRangeBlock(sb, "mesh", s.MeshRanges);
            WriteRangeBlock(sb, "tectonics", s.TectonicRanges);
            WriteRangeBlock(sb, "spherical_harmonics", s.SphericalHarmonicsRanges);
        }

        WriteText(BiomeEditorModel.SubtypeFilePath(family), sb.ToString());
    }

    private static void WriteRangeBlock(StringBuilder sb, string blockKey, Dictionary<string, FloatRange> ranges)
    {
        if (ranges.Count == 0) return;
        YamlIndent.AppendLine(sb, 2, $"{blockKey}:");
        foreach (var kvp in ranges.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            var r = kvp.Value;
            YamlIndent.AppendLine(sb, 3, $"{kvp.Key}: [{FormatFloat(r.Min)}, {FormatFloat(r.Max)}]");
        }
    }

    private static void WriteStringList(StringBuilder sb, string key, List<string> items)
    {
        if (items.Count == 0)
        {
            YamlIndent.AppendLine(sb, 2, $"{key}: []");
            return;
        }
        YamlIndent.AppendLine(sb, 2, $"{key}: [{string.Join(", ", items)}]");
    }

    private static string YamlScalar(string s)
    {
        if (string.IsNullOrEmpty(s)) return "\"\"";
        if (s.IndexOfAny(new[] { ':', '#', '\'', '"', '[', ']', '{', '}', '\n', ',' }) >= 0)
            return "\"" + s.Replace("\"", "\\\"") + "\"";
        return s;
    }

    private static string FormatHex(Color c)
    {
        int r = Mathf.Clamp((int)Mathf.Round(c.R * 255f), 0, 255);
        int g = Mathf.Clamp((int)Mathf.Round(c.G * 255f), 0, 255);
        int b = Mathf.Clamp((int)Mathf.Round(c.B * 255f), 0, 255);
        return $"#{r:X2}{g:X2}{b:X2}";
    }

    // ── Assigner config ─────────────────────────────────────────────────

    private static void WriteAssignerConfig(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Biome assigner config — drives ConfigurableBiomeAssigner per RockyPlanetSubtype.");
        sb.AppendLine("# Auto-generated by BiomeEditor. Hand edits will round-trip but comments may be lost.");
        sb.AppendLine();
        sb.AppendLine("assigners:");

        foreach (var subtype in Enum.GetValues<RockyPlanetSubtype>())
        {
            if (!model.Assigners.TryGetValue(subtype, out var entry)) continue;
            sb.Append(YamlIndent.Of(1)).Append(subtype).AppendLine(":");
            WriteMoisture(sb, entry.Moisture);
            WriteRules(sb, entry.Rules);
            sb.AppendLine();
        }

        WriteText(BiomeEditorModel.AssignerPath, sb.ToString());
    }

    private static void WriteMoisture(StringBuilder sb, MoistureParams m)
    {
        YamlIndent.AppendLine(sb, 2, "moisture:");
        YamlIndent.AppendLine(sb, 3, $"mode: {(m.Mode == MoistureMode.UniformRandom ? "uniform_random" : "whittaker")}");
        if (m.Mode == MoistureMode.Whittaker)
        {
            YamlIndent.AppendLine(sb, 3, $"base_offset: {FormatFloat(m.BaseOffset)}");
            YamlIndent.AppendLine(sb, 3, $"latitude_factor_divisor: {FormatFloat(m.LatitudeFactorDivisor)}");
            YamlIndent.AppendLine(sb, 3, $"size_factor_divisor: {FormatFloat(m.SizeFactorDivisor)}");
            YamlIndent.AppendLine(sb, 3, $"random_min: {FormatFloat(m.RandomMin)}");
            YamlIndent.AppendLine(sb, 3, $"random_max: {FormatFloat(m.RandomMax)}");
            YamlIndent.AppendLine(sb, 3, $"max_moisture: {FormatFloat(m.MaxMoisture)}");
            YamlIndent.AppendLine(sb, 3, $"constant_offset: {FormatFloat(m.ConstantOffset)}");
        }
        else
        {
            YamlIndent.AppendLine(sb, 3, $"random_min: {FormatFloat(m.RandomMin)}");
            YamlIndent.AppendLine(sb, 3, $"random_max: {FormatFloat(m.RandomMax)}");
        }
    }

    private static void WriteRules(StringBuilder sb, List<BiomeRule> rules)
    {
        YamlIndent.AppendLine(sb, 2, "rules:");
        foreach (var rule in rules)
        {
            var conds = new List<string>();
            if (rule.When.HeightAbove.HasValue) conds.Add($"height_above: {FormatFloat(rule.When.HeightAbove.Value)}");
            if (rule.When.HeightBelow.HasValue) conds.Add($"height_below: {FormatFloat(rule.When.HeightBelow.Value)}");
            if (rule.When.MoistureAbove.HasValue) conds.Add($"moisture_above: {FormatFloat(rule.When.MoistureAbove.Value)}");
            if (rule.When.MoistureBelow.HasValue) conds.Add($"moisture_below: {FormatFloat(rule.When.MoistureBelow.Value)}");
            if (rule.When.AbsLatitudeAbove.HasValue) conds.Add($"abs_latitude_above: {FormatFloat(rule.When.AbsLatitudeAbove.Value)}");
            if (rule.When.AbsLatitudeBelow.HasValue) conds.Add($"abs_latitude_below: {FormatFloat(rule.When.AbsLatitudeBelow.Value)}");
            string when = conds.Count == 0 ? "{}" : "{ " + string.Join(", ", conds) + " }";
            YamlIndent.AppendLine(sb, 3, $"- {{ biome: {rule.Biome}, when: {when} }}");
        }
    }

    // ── Biome resource config ───────────────────────────────────────────

    private static void WriteBiomeResourceConfig(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("biomes:");
        bool first = true;
        // Preserve declaration order from enum.
        foreach (var biome in Enum.GetValues<Biome.BiomeType>())
        {
            if (!model.BiomeResources.TryGetValue(biome, out var entry)) continue;
            if (!first) sb.AppendLine();
            first = false;
            YamlIndent.AppendLine(sb, 1, $"- biome: {biome}");
            YamlIndent.AppendLine(sb, 2, "groupAvailability:");
            foreach (var kvp in entry.Groups.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                YamlIndent.AppendLine(sb, 3, $"{kvp.Key}: {kvp.Value}");
            }
        }
        WriteText(BiomeEditorModel.BiomeResourcePath, sb.ToString());
    }

    // ── Planetary resource config (rockyPlanetSubtypes only) ────────────

    private static void WritePlanetaryResourceConfig(BiomeEditorModel model)
    {
        Dictionary<object, object>? raw = LoadRawDict(BiomeEditorModel.PlanetaryResourcePath);
        raw ??= new Dictionary<object, object>();

        var rockyList = new List<object>();
        foreach (var subtype in Enum.GetValues<RockyPlanetSubtype>())
        {
            if (!model.SubtypeResources.TryGetValue(subtype, out var s)) continue;
            var entry = new Dictionary<object, object>
            {
                ["subtype"] = subtype.ToString(),
                ["resourceGroups"] = s.ResourceGroups.Cast<object>().ToList(),
                ["addResources"] = s.AddResources.Cast<object>().ToList(),
                ["removeResources"] = s.RemoveResources.Cast<object>().ToList(),
                ["baseResourceWeight"] = (double)s.BaseResourceWeight,
            };
            rockyList.Add(entry);
        }
        raw["rockyPlanetSubtypes"] = rockyList;

        WriteRawDict(BiomeEditorModel.PlanetaryResourcePath, raw);
    }

    // ── Resource groups ─────────────────────────────────────────────────

    private static void WriteResourceGroups(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Resource Groups — reusable sets of resource IDs");
        sb.AppendLine("# Referenced by subtype configs in planetary_resource_config.yaml");
        sb.AppendLine();
        bool first = true;
        foreach (var g in model.ResourceGroups)
        {
            if (string.IsNullOrEmpty(g.GroupName)) continue;
            if (!first) sb.AppendLine();
            first = false;
            sb.Append(g.GroupName).AppendLine(":");
            foreach (var id in g.ResourceIds)
                YamlIndent.AppendLine(sb, 1, $"- {id}");
        }
        WriteText(BiomeEditorModel.ResourceGroupsPath, sb.ToString());
    }

    // ── Atmosphere templates (SystemGen/*.yaml) ─────────────────────────

    private static void WriteAtmosphereTemplates(BiomeEditorModel model)
    {
        foreach (var edit in model.AtmosphereTemplates.Values)
        {
            if (!edit.IsDirty) continue;
            var raw = LoadRawDict(edit.SourceFilePath);
            if (raw == null) continue;

            object? root = raw.ContainsKey("celestial") ? raw["celestial"]
                         : raw.ContainsKey("satellite_group") ? raw["satellite_group"]
                         : null;
            if (root is not Dictionary<object, object> rdict) continue;
            if (!rdict.TryGetValue("template", out var tmpl) || tmpl is not Dictionary<object, object> tdict)
                continue;

            tdict["atmosphere"] = new List<object> { (double)edit.AtmosphereMin, (double)edit.AtmosphereMax };
            WriteRawDict(edit.SourceFilePath, raw);
        }
    }

    // ── Raw dict round-trip helpers ─────────────────────────────────────

    private static Dictionary<object, object>? LoadRawDict(string path)
    {
        if (!Godot.FileAccess.FileExists(path)) return null;
        using var f = Godot.FileAccess.Open(path, Godot.FileAccess.ModeFlags.Read);
        if (f == null) return null;
        string text = f.GetAsText();
        try
        {
            var d = new DeserializerBuilder().Build();
            return d.Deserialize<Dictionary<object, object>>(text);
        }
        catch (Exception ex)
        {
            GameLogger.Error($"BiomeEditorYamlIO: failed deserialize {path}: {ex.Message}");
            return null;
        }
    }

    private static void WriteRawDict(string path, Dictionary<object, object> raw)
    {
        try
        {
            var serializer = new SerializerBuilder()
                .WithDefaultScalarStyle(YamlDotNet.Core.ScalarStyle.Plain)
                .Build();
            string text = serializer.Serialize(raw);
            WriteText(path, text);
        }
        catch (Exception ex)
        {
            GameLogger.Error($"BiomeEditorYamlIO: failed serialize {path}: {ex.Message}");
        }
    }

    // ── File helpers ────────────────────────────────────────────────────

    private static void WriteText(string filePath, string content)
    {
        var file = Godot.FileAccess.Open(filePath, Godot.FileAccess.ModeFlags.Write);
        if (file == null)
        {
            var err = Godot.FileAccess.GetOpenError();
            throw new InvalidOperationException($"BiomeEditor: cannot write {filePath} ({err})");
        }
        try { file.StoreString(content); }
        finally { file.Close(); }
    }

    private static string FormatFloat(float value)
    {
        if (Mathf.IsEqualApprox(value, Mathf.Round(value)))
            return ((int)value).ToString(CultureInfo.InvariantCulture);
        return value.ToString("0.######", CultureInfo.InvariantCulture);
    }
}
#endif
