#if DEBUG
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Godot;
using ProceduralGeneration.BiomeSystem;
using Structures.Enums;
using UtilityLibrary;
using YamlDotNet.Serialization;

namespace DeveloperTools.BiomeEditor;

/// <summary>
/// Writes BiomeEditorModel contents back to disk across the five source YAML files.
/// Files fully owned by the editor (assigner config, biome resource config, resource groups)
/// are emitted from scratch; multi-section files (planetary_resource_config, SystemGen)
/// are loaded into a dictionary, mutated in place, and re-serialized to preserve unrelated keys.
/// </summary>
public static class BiomeEditorYamlIO
{
    public static void WriteAll(BiomeEditorModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        WriteAssignerConfig(model);
        WriteBiomeResourceConfig(model);
        WritePlanetaryResourceConfig(model);
        WriteResourceGroups(model);
        WriteAtmosphereTemplates(model);

        // Reset dirty flags.
        foreach (var a in model.Assigners.Values) a.IsDirty = false;
        foreach (var b in model.BiomeResources.Values) b.IsDirty = false;
        foreach (var s in model.SubtypeResources.Values) s.IsDirty = false;
        foreach (var g in model.ResourceGroups) { g.IsDirty = false; g.IsNew = false; }
        foreach (var t in model.AtmosphereTemplates.Values) t.IsDirty = false;
    }

    // ── Assigner config ─────────────────────────────────────────────────

    private static void WriteAssignerConfig(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Biome assigner config — drives ConfigurableBiomeAssigner per RockyPlanetSubtype.");
        sb.AppendLine("# Auto-generated by BiomeEditor. Hand edits will round-trip but comments may be lost.");
        sb.AppendLine();
        sb.AppendLine("assigners:");

        foreach (var subtype in Enum.GetValues<RockyPlanetSubtype>())
        {
            if (!model.Assigners.TryGetValue(subtype, out var entry)) continue;
            sb.Append(YamlIndent.Of(1)).Append(subtype).AppendLine(":");
            WriteMoisture(sb, entry.Moisture);
            WriteRules(sb, entry.Rules);
            sb.AppendLine();
        }

        WriteText(BiomeEditorModel.AssignerPath, sb.ToString());
    }

    private static void WriteMoisture(StringBuilder sb, MoistureParams m)
    {
        YamlIndent.AppendLine(sb, 2, "moisture:");
        YamlIndent.AppendLine(sb, 3, $"mode: {(m.Mode == MoistureMode.UniformRandom ? "uniform_random" : "whittaker")}");
        if (m.Mode == MoistureMode.Whittaker)
        {
            YamlIndent.AppendLine(sb, 3, $"base_offset: {FormatFloat(m.BaseOffset)}");
            YamlIndent.AppendLine(sb, 3, $"latitude_factor_divisor: {FormatFloat(m.LatitudeFactorDivisor)}");
            YamlIndent.AppendLine(sb, 3, $"size_factor_divisor: {FormatFloat(m.SizeFactorDivisor)}");
            YamlIndent.AppendLine(sb, 3, $"random_min: {FormatFloat(m.RandomMin)}");
            YamlIndent.AppendLine(sb, 3, $"random_max: {FormatFloat(m.RandomMax)}");
            YamlIndent.AppendLine(sb, 3, $"max_moisture: {FormatFloat(m.MaxMoisture)}");
            YamlIndent.AppendLine(sb, 3, $"constant_offset: {FormatFloat(m.ConstantOffset)}");
        }
        else
        {
            YamlIndent.AppendLine(sb, 3, $"random_min: {FormatFloat(m.RandomMin)}");
            YamlIndent.AppendLine(sb, 3, $"random_max: {FormatFloat(m.RandomMax)}");
        }
    }

    private static void WriteRules(StringBuilder sb, List<BiomeRule> rules)
    {
        YamlIndent.AppendLine(sb, 2, "rules:");
        foreach (var rule in rules)
        {
            var conds = new List<string>();
            if (rule.When.HeightAbove.HasValue) conds.Add($"height_above: {FormatFloat(rule.When.HeightAbove.Value)}");
            if (rule.When.HeightBelow.HasValue) conds.Add($"height_below: {FormatFloat(rule.When.HeightBelow.Value)}");
            if (rule.When.MoistureAbove.HasValue) conds.Add($"moisture_above: {FormatFloat(rule.When.MoistureAbove.Value)}");
            if (rule.When.MoistureBelow.HasValue) conds.Add($"moisture_below: {FormatFloat(rule.When.MoistureBelow.Value)}");
            if (rule.When.AbsLatitudeAbove.HasValue) conds.Add($"abs_latitude_above: {FormatFloat(rule.When.AbsLatitudeAbove.Value)}");
            if (rule.When.AbsLatitudeBelow.HasValue) conds.Add($"abs_latitude_below: {FormatFloat(rule.When.AbsLatitudeBelow.Value)}");
            string when = conds.Count == 0 ? "{}" : "{ " + string.Join(", ", conds) + " }";
            YamlIndent.AppendLine(sb, 3, $"- {{ biome: {rule.Biome}, when: {when} }}");
        }
    }

    // ── Biome resource config ───────────────────────────────────────────

    private static void WriteBiomeResourceConfig(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("biomes:");
        bool first = true;
        // Preserve declaration order from enum.
        foreach (var biome in Enum.GetValues<Biome.BiomeType>())
        {
            if (!model.BiomeResources.TryGetValue(biome, out var entry)) continue;
            if (!first) sb.AppendLine();
            first = false;
            YamlIndent.AppendLine(sb, 1, $"- biome: {biome}");
            YamlIndent.AppendLine(sb, 2, "resourceWeightModifiers:");
            foreach (var kvp in entry.Weights.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                YamlIndent.AppendLine(sb, 3, $"{kvp.Key}: {FormatFloat(kvp.Value)}");
            }
        }
        WriteText(BiomeEditorModel.BiomeResourcePath, sb.ToString());
    }

    // ── Planetary resource config (rockyPlanetSubtypes only) ────────────

    private static void WritePlanetaryResourceConfig(BiomeEditorModel model)
    {
        Dictionary<object, object>? raw = LoadRawDict(BiomeEditorModel.PlanetaryResourcePath);
        raw ??= new Dictionary<object, object>();

        var rockyList = new List<object>();
        foreach (var subtype in Enum.GetValues<RockyPlanetSubtype>())
        {
            if (!model.SubtypeResources.TryGetValue(subtype, out var s)) continue;
            var entry = new Dictionary<object, object>
            {
                ["subtype"] = subtype.ToString(),
                ["resourceGroups"] = s.ResourceGroups.Cast<object>().ToList(),
                ["addResources"] = s.AddResources.Cast<object>().ToList(),
                ["removeResources"] = s.RemoveResources.Cast<object>().ToList(),
                ["baseResourceWeight"] = (double)s.BaseResourceWeight,
            };
            rockyList.Add(entry);
        }
        raw["rockyPlanetSubtypes"] = rockyList;

        WriteRawDict(BiomeEditorModel.PlanetaryResourcePath, raw);
    }

    // ── Resource groups ─────────────────────────────────────────────────

    private static void WriteResourceGroups(BiomeEditorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Resource Groups — reusable sets of resource IDs");
        sb.AppendLine("# Referenced by subtype configs in planetary_resource_config.yaml");
        sb.AppendLine();
        bool first = true;
        foreach (var g in model.ResourceGroups)
        {
            if (string.IsNullOrEmpty(g.GroupName)) continue;
            if (!first) sb.AppendLine();
            first = false;
            sb.Append(g.GroupName).AppendLine(":");
            foreach (var id in g.ResourceIds)
                YamlIndent.AppendLine(sb, 1, $"- {id}");
        }
        WriteText(BiomeEditorModel.ResourceGroupsPath, sb.ToString());
    }

    // ── Atmosphere templates (SystemGen/*.yaml) ─────────────────────────

    private static void WriteAtmosphereTemplates(BiomeEditorModel model)
    {
        foreach (var edit in model.AtmosphereTemplates.Values)
        {
            if (!edit.IsDirty) continue;
            var raw = LoadRawDict(edit.SourceFilePath);
            if (raw == null) continue;

            object? root = raw.ContainsKey("celestial") ? raw["celestial"]
                         : raw.ContainsKey("satellite_group") ? raw["satellite_group"]
                         : null;
            if (root is not Dictionary<object, object> rdict) continue;
            if (!rdict.TryGetValue("template", out var tmpl) || tmpl is not Dictionary<object, object> tdict)
                continue;

            tdict["atmosphere"] = new List<object> { (double)edit.AtmosphereMin, (double)edit.AtmosphereMax };
            WriteRawDict(edit.SourceFilePath, raw);
        }
    }

    // ── Raw dict round-trip helpers ─────────────────────────────────────

    private static Dictionary<object, object>? LoadRawDict(string path)
    {
        if (!Godot.FileAccess.FileExists(path)) return null;
        using var f = Godot.FileAccess.Open(path, Godot.FileAccess.ModeFlags.Read);
        if (f == null) return null;
        string text = f.GetAsText();
        try
        {
            var d = new DeserializerBuilder().Build();
            return d.Deserialize<Dictionary<object, object>>(text);
        }
        catch (Exception ex)
        {
            GameLogger.Error($"BiomeEditorYamlIO: failed deserialize {path}: {ex.Message}");
            return null;
        }
    }

    private static void WriteRawDict(string path, Dictionary<object, object> raw)
    {
        try
        {
            var serializer = new SerializerBuilder()
                .WithDefaultScalarStyle(YamlDotNet.Core.ScalarStyle.Plain)
                .Build();
            string text = serializer.Serialize(raw);
            WriteText(path, text);
        }
        catch (Exception ex)
        {
            GameLogger.Error($"BiomeEditorYamlIO: failed serialize {path}: {ex.Message}");
        }
    }

    // ── File helpers ────────────────────────────────────────────────────

    private static void WriteText(string filePath, string content)
    {
        var file = Godot.FileAccess.Open(filePath, Godot.FileAccess.ModeFlags.Write);
        if (file == null)
        {
            var err = Godot.FileAccess.GetOpenError();
            throw new InvalidOperationException($"BiomeEditor: cannot write {filePath} ({err})");
        }
        try { file.StoreString(content); }
        finally { file.Close(); }
    }

    private static string FormatFloat(float value)
    {
        if (Mathf.IsEqualApprox(value, Mathf.Round(value)))
            return ((int)value).ToString(CultureInfo.InvariantCulture);
        return value.ToString("0.######", CultureInfo.InvariantCulture);
    }
}
#endif
