biomes:
  - biome: Tundra
    groupAvailability:
      basicFuels: Normal
      commonOres: Normal
      frozenVolatiles: Frequent
      industrialMaterials: Scarce

  - biome: Icecap
    groupAvailability:
      basicFuels: Frequent
      commonOres: Scarce
      frozenVolatiles: Abundant
      industrialMaterials: Rare

  - biome: Desert
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Frequent
      preciousOres: Scarce
      radioactiveOres: Normal

  - biome: Grassland
    groupAvailability:
      basicFuels: Frequent
      commonOres: Frequent
      flora: Normal
      habitableFoods: Frequent
      industrialMaterials: Normal

  - biome: Forest
    groupAvailability:
      basicFuels: Frequent
      commonOres: Scarce
      flora: Abundant
      habitableFoods: Frequent
      industrialMaterials: Normal

  - biome: Rainforest
    groupAvailability:
      basicFuels: Abundant
      commonOres: Scarce
      flora: Abundant
      habitableFoods: Abundant
      industrialMaterials: Normal

  - biome: Taiga
    groupAvailability:
      basicFuels: Normal
      commonOres: Frequent
      flora: Abundant
      frozenVolatiles: Normal
      habitableFoods: Scarce
      industrialMaterials: Scarce

  - biome: Ocean
    groupAvailability:
      basicFuels: Abundant
      commonOres: Rare
      frozenVolatiles: Scarce
      industrialMaterials: Normal
      preciousOres: Scarce

  - biome: Coastal
    groupAvailability:
      basicFuels: Frequent
      commonOres: Normal
      habitableFoods: Scarce
      industrialMaterials: Frequent

  - biome: Mountain
    groupAvailability:
      commonOres: Abundant
      industrialMaterials: Normal
      preciousOres: Frequent
      radioactiveOres: Scarce

  - biome: SandDesert
    groupAvailability:
      commonOres: Scarce
      industrialMaterials: Abundant
      preciousOres: Scarce
      radioactiveOres: Frequent

  - biome: StoneDesert
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Frequent
      preciousOres: Normal
      radioactiveOres: Normal

  - biome: Swamp
    groupAvailability:
      basicFuels: Frequent
      commonOres: Scarce
      habitableFoods: Frequent
      industrialMaterials: Normal

  - biome: Glacier
    groupAvailability:
      basicFuels: Frequent
      commonOres: Rare
      frozenVolatiles: Abundant

  - biome: FrozenPlain
    groupAvailability:
      basicFuels: Normal
      commonOres: Normal
      frozenVolatiles: Frequent
      industrialMaterials: Scarce

  - biome: RustedPlain
    groupAvailability:
      commonOres: Abundant
      industrialMaterials: Scarce
      preciousOres: Normal
      radioactiveOres: Scarce

  - biome: RustedMountain
    groupAvailability:
      commonOres: Abundant
      industrialMaterials: Scarce
      preciousOres: Frequent
      radioactiveOres: Normal

  - biome: RustedDesert
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Frequent
      preciousOres: Normal
      radioactiveOres: Normal

  - biome: ScouredPlain
    groupAvailability:
      commonOres: Normal
      industrialMaterials: Scarce
      preciousOres: Frequent
      radioactiveOres: Frequent
      rareOres: Scarce

  - biome: LavaOcean
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Normal
      preciousOres: Normal
      radioactiveOres: Normal

  - biome: VolcanicPeak
    groupAvailability:
      commonOres: Abundant
      industrialMaterials: Normal
      preciousOres: Frequent
      radioactiveOres: Frequent

  - biome: AshPlain
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Frequent
      preciousOres: Scarce
      radioactiveOres: Normal

  - biome: ObsidianField
    groupAvailability:
      commonOres: Normal
      industrialMaterials: Abundant
      preciousOres: Normal
      radioactiveOres: Scarce

  - biome: VolcanicPlain
    groupAvailability:
      commonOres: Frequent
      industrialMaterials: Frequent
      preciousOres: Scarce
      radioactiveOres: Normal

  - biome: ShallowOcean
    groupAvailability:
      basicFuels: Abundant
      commonOres: Scarce
      frozenVolatiles: Scarce
      industrialMaterials: Scarce

  - biome: DeepOcean
    groupAvailability:
      basicFuels: Abundant
      commonOres: Rare
      frozenVolatiles: Normal
      preciousOres: Scarce
