[celestial.template]
position = [0, 0, 0]
velocity = [0, 0, 0]
mass = 1000000
size = 10

[celestial.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[5, 12]]
num_abberations = 1
num_deformation_cycles = 1

[celestial.mesh.tectonic]
num_continents = [1, 1]
stress_scale = [1.0, 5.0]
shear_scale = [0.5, 2.0]
max_propagation_distance = [0.02, 0.2]
propagation_falloff = [0.5, 1.0]
inactive_stress_threshold = [0.02, 0.2]
general_height_scale = [0.5, 1.5]
general_shear_scale = [0.5, 1.5]
general_compression_scale = [1.5, 2.5]
general_transform_scale = [1.2, 1.8]
