[celestial.template]
position = [500, 0, 0]
velocity = [0, 7, 0]
mass = 1000
size = 35

[celestial.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[10, 13]]
num_abberations = 0
num_deformation_cycles = 0

[celestial.mesh.tectonic]
num_continents = [3, 8]
stress_scale = [0.8, 1.0]
shear_scale = [0.2, 1.0]
max_propagation_distance = [0.01, 0.01]
propagation_falloff = [0.2, 0.2]
inactive_stress_threshold = [0.01, 0.01]
general_height_scale = [0.8, 1.2]
general_shear_scale = [0.8, 1.2]
general_compression_scale = [1.0, 1.0]
general_transform_scale = [1.0, 1.0]
