[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Hephaestus",
  "Vulcan",
  "Gaia",
  "Terra",
  "Geb",
  "Khnum",
  "Ptah",
  "Jord",
  "Surtr",
  "Skadi",
  "Sindri",
  "Brokk",
  "Brigid",
  "Goibniu",
  "Ogun",
  "Ilmarinen",
  "Svarog",
  "Veles",
  "Kanayago",
  "Kagutsuchi",
  "Pele",
  "Ruaumoko",
  "Papatuanuku",
  "Agni",
  "Prithvi",
  "Himavat",
  "Vishvakarman",
  "Tvastar",
  "Tepeyollotl",
  "Tlaltecuhtli",
  "Xiuhtecuhtli",
  "Coatlicue",
  "Pachamama",
  "Supay",
  "Ataentsic",
  "Houtu",
  "Yu the Great",
  "Ninhursag",
  "Ki",
  "Wayland",
  "Tubal-Cain",
  "Ala",
  "Asase Yaa",
  "Hineahuone",
  "Tatenen",
  "Naga Padoha",
  "Cybele",
  "Rhea",
  "Demeter",
  "Ereshkigal",
]

[scientists]
names = [
  "Charles Lyell",
  "James Hutton",
  "Alfred Wegener",
  "Marie Tharp",
  "Inge Lehmann",
  "Beno Gutenberg",
  "Andrija Mohorovicic",
  "John Tuzo Wilson",
  "Harry Hess",
  "J Harlen Bretz",
  "Grove Karl Gilbert",
  "Walther Penck",
  "Nicolas Steno",
  "Mary Anning",
  "Florence Bascom",
  "William Smith",
  "Eduard Suess",
  "Arthur Holmes",
  "Reginald Daly",
  "Clair Patterson",
  "Keith Runcorn",
  "Dan McKenzie",
  "Xavier Le Pichon",
  "Jason Morgan",
  "Tanya Atwater",
  "Marion King Hubbert",
  "Richard Dixon Oldham",
  "Emil Wiechert",
  "Victor Goldschmidt",
  "Frederick Vine",
  "Drummond Matthews",
  "Susan Kieffer",
  "Don L Anderson",
  "Hiroo Kanamori",
  "Keiiti Aki",
  "Clarence King",
  "William Morris Davis",
  "Thomas Jaggar",
  "Katia Krafft",
  "Maurice Krafft",
  "Haroun Tazieff",
  "Norman L Bowen",
  "Walter Alvarez",
  "Jack Oliver",
  "Bruce Heezen",
  "Robert Dietz",
  "Ellen Stofan",
  "Iain Stewart",
  "Chris Newhall",
  "Stephen Sparks",
]

[explorers]
names = [
  "Alexander von Humboldt",
  "John Wesley Powell",
  "Ernest Shackleton",
  "Roald Amundsen",
  "Robert Falcon Scott",
  "Fridtjof Nansen",
  "Douglas Mawson",
  "Richard E Byrd",
  "John Rae",
  "Mungo Park",
  "Richard Francis Burton",
  "James Bruce",
  "Mary Kingsley",
  "Gertrude Bell",
  "Isabelle Eberhardt",
  "Wilfred Thesiger",
  "Aurel Stein",
  "Sven Hedin",
  "Nain Singh Rawat",
  "Pandit Kishen Singh",
  "Alexandra David-Neel",
  "Paul Emile Victor",
  "Knud Rasmussen",
  "Hiram Bingham",
  "Helge Ingstad",
  "Vilhjalmur Stefansson",
  "Ranulph Fiennes",
  "Benedict Allen",
  "Reinhold Messner",
  "Edmund Hillary",
  "Tenzing Norgay",
  "Apsley Cherry-Garrard",
  "Osa Johnson",
  "Martin Johnson",
  "Isabella Bird",
  "Freya Stark",
  "Pytheas",
  "Ibn Fadlan",
  "Xuanzang",
  "Meriwether Lewis",
  "William Clark",
  "James Clark Ross",
  "Frank Wild",
  "Henry Hudson",
  "Charles Sturt",
  "John McDouall Stuart",
  "Robert O'Hara Burke",
  "William John Wills",
  "Robert Peary",
  "Matthew Henson",
]

[adjectives]
names = [
  "Basaltic",
  "Ferric",
  "Rugged",
  "Tectonic",
  "Stonebound",
  "Ironbound",
  "Rockribbed",
  "Stoneclad",
  "Ironclad",
  "Granitehewn",
  "Obsidianborn",
  "Basalthewn",
  "Magmaforged",
  "Lavaforged",
  "Ashmantled",
  "Scoriastrown",
  "Riftwrought",
  "Faultscarred",
  "Bedrockbound",
  "Cragborn",
  "Cliffworn",
  "Seamed",
  "Striated",
  "Serrated",
  "Weathered",
  "Gritlined",
  "Gravelly",
  "Bouldered",
  "Talusstrewn",
  "Schistose",
  "Gneissic",
  "Ultrabasic",
  "Mafic",
  "Felsic",
  "Pyroclastic",
  "Plutonic",
  "Orogenic",
  "Lithic",
  "Petrous",
  "Adamantine",
  "Hardpacked",
  "Flinty",
  "Ironrich",
  "Stonefast",
  "Earthfast",
  "Seismic",
  "Basaltblack",
  "Rifted",
  "Crusted",
  "Dustblown",
]

[template]
position = [150, 0, 0]
velocity = [0, 10, 0]
mass = 10
size = 12

[mesh.base_mesh]
subdivisions = 2
vertices_per_edge = [3, 5]
num_abberations = 3
num_deformation_cycles = 3

[mesh.tectonic]
num_continents = [25, 40]
stress_scale = [3.0, 8.0]
shear_scale = [1.0, 1.7]
max_propagation_distance = [0.1, 0.4]
propagation_falloff = [0.8, 1.5]
inactive_stress_threshold = [0.01, 0.1]
general_height_scale = [0.8, 1.2]
general_shear_scale = [10.0, 18.0]
general_compression_scale = [20.0, 40.0]
general_transform_scale = [1.1, 1.4]
