using System;
using Godot;
using UI;
using UtilityLibrary;

namespace Scenes
{
    /// <summary>
    /// Main game scene controller. Receives generated bodies from LoadingScreen.
    /// Bodies are already generated and added to system_container by LoadingScreen.
    /// </summary>
    public partial class GameScene : Node3D
    {
        public override void _Ready()
        {
            GameLogger.EnterFunction(nameof(_Ready));

            // Instantiate Construction HUD
            var constructionHudScene = GD.Load<PackedScene>(
                "res://UI/Construction/ConstructionHUD.tscn"
            );
            if (constructionHudScene != null)
            {
                AddChild(constructionHudScene.Instantiate());
                GameLogger.Debug("ConstructionHUD added to GameScene");
            }

            // Instantiate Main Game UI (includes ToastSystem)
            var mainGameUIScene = GD.Load<PackedScene>("res://UI/MainGameUI.tscn");
            if (mainGameUIScene != null)
            {
                AddChild(mainGameUIScene.Instantiate());
                GameLogger.Debug("MainGameUI added to GameScene");
            }

            // Check if bodies were generated into our system_container
            // (should have been done by LoadingScreen)
            var systemContainer = GetNodeOrNull<Node>("system_container");
            if (systemContainer != null)
            {
                int bodyCount = systemContainer.GetChildCount();
                if (bodyCount > 0)
                {
                    GameLogger.Info($"GameScene loaded with {bodyCount} bodies in system_container");
                }
                else
                {
                    GameLogger.Warning("GameScene system_container is empty - no bodies were generated");
                }
            }
            else
            {
                GameLogger.Error("GameScene system_container not found");
            }

            // Clear any template selection (handled by LoadingScreen)
            if (SignalBus.Instance != null)
            {
                SignalBus.Instance.SelectedTemplate = null;
            }

            GameLogger.Info("Game scene loaded (bodies generated by LoadingScreen)");
            GameLogger.ExitFunction(nameof(_Ready));
        }

        private void ReturnToMainMenu()
        {
            GameLogger.Info("Returning to MainMenu");
            GetTree().ChangeSceneToFile("res://Scenes/MainMenu.tscn");
        }
    }
}
