using Godot;
using UtilityLibrary;

namespace Scenes
{
    /// <summary>
    /// Main game scene controller. Receives generated bodies from LoadingScreen.
    /// Bodies are already generated and added to system_container by LoadingScreen.
    /// </summary>
    public partial class GameScene : Node3D
    {
        private Node? _systemContainer;

        public override void _Ready()
        {
            GameLogger.EnterFunction(nameof(_Ready));

            // Instantiate Main Game UI (includes ToastSystem)
            var mainGameUIScene = GD.Load<PackedScene>("res://UI/MainGameUI.tscn");
            if (mainGameUIScene != null)
            {
                AddChild(mainGameUIScene.Instantiate());
                GameLogger.Debug("MainGameUI added to GameScene");
            }

            // Ensure system_container has SystemData
            var systemContainer = GetNodeOrNull<Node>("system_container");
            _systemContainer = systemContainer;
            if (systemContainer != null)
            {
                // Add SystemData if not present
                if (systemContainer.GetNodeOrNull<Structures.GameState.SystemData>("SystemData") == null)
                {
                    var systemData = new Structures.GameState.SystemData { Name = "SystemData" };
                    systemContainer.AddChild(systemData);
                    GameLogger.Debug("SystemData added to system_container");
                }

                // Add CompanyDataTracker before EconomyTracker so the economy can rely on
                // CompanyDataTracker.Instance being set for buy/sell currency flow.
                if (systemContainer.GetNodeOrNull<Structures.GameState.CompanyDataTracker>("CompanyDataTracker") == null)
                {
                    var companyTracker = new Structures.GameState.CompanyDataTracker { Name = "CompanyDataTracker" };
                    systemContainer.AddChild(companyTracker);
                    GameLogger.Debug("CompanyDataTracker added to system_container");
                }

                if (systemContainer.GetNodeOrNull<Structures.GameState.EconomyTracker>("EconomyTracker") == null)
                {
                    var economyTracker = new Structures.GameState.EconomyTracker { Name = "EconomyTracker" };
                    systemContainer.AddChild(economyTracker);
                    GameLogger.Debug("EconomyTracker added to system_container");
                }

                // TimeKeeper added after SystemData so the ManufactureTickEngine is already running
                // (SystemData._Ready starts it), and before RestoreSession so it is in the
                // "save_serializable" group when the loader restores the clock.
                if (systemContainer.GetNodeOrNull<Structures.GameState.TimeKeeper>("TimeKeeper") == null)
                {
                    var timeKeeper = new Structures.GameState.TimeKeeper { Name = "TimeKeeper" };
                    systemContainer.AddChild(timeKeeper);
                    GameLogger.Debug("TimeKeeper added to system_container");
                }

                // If a save is being loaded, restore company/economy/session state now that the
                // trackers exist and have run their _Ready (Instance set, market seeded).
                if (UtilityLibrary.SaveLoad.SaveLoader.IsLoadPending)
                {
                    UtilityLibrary.SaveLoad.SaveLoader.RestoreSession(systemContainer);
                }

                int bodyCount = systemContainer.GetChildCount();
                if (bodyCount > 0)
                {
                    GameLogger.Info($"GameScene loaded with {bodyCount} bodies in system_container");
                }
                else
                {
                    GameLogger.Warning("GameScene system_container is empty - no bodies were generated");
                }
            }
            else
            {
                GameLogger.Error("GameScene system_container not found");
            }

            // Clear any template selection (handled by LoadingScreen)
            if (SignalBus.Instance != null)
            {
                SignalBus.Instance.SelectedTemplate = null;
            }

            GameLogger.Info("Game scene loaded (bodies generated by LoadingScreen)");
            GameLogger.ExitFunction(nameof(_Ready));
        }

        public override void _UnhandledKeyInput(InputEvent @event)
        {
            if (@event is InputEventKey { Pressed: true, Echo: false, Keycode: Key.F5 }
                && _systemContainer != null)
            {
                var path = UtilityLibrary.SaveLoad.SaveManager.Save(_systemContainer);
                GameLogger.Info(path != null ? $"Quicksaved to {path}" : "Quicksave failed");
            }
        }

        private void ReturnToMainMenu()
        {
            GameLogger.Info("Returning to MainMenu");
            GetTree().ChangeSceneToFile("res://Scenes/MainMenu.tscn");
        }
    }
}
